//! Extracts a compact subset of the Android SDK's `api-versions.xml` into the text format
//! consumed by the `java_api!` macro.
//!
//! `api-versions.xml` is the database Android Lint's `NewApi` check uses: it records, for every
//! class, method and field of the platform, the API level it was introduced in. Vendoring the
//! whole file (5.7 MB) into the repository is not desirable, so only the classes listed in
//! `classes.txt` and their supertypes are extracted.
//!
//! Usage:
//!
//! ```text
//! cargo run -p android_api_metadata -- \
//!     --classes crates/unienc_android_mc/java-api/classes.txt \
//!     --out     crates/unienc_android_mc/java-api/android-api-versions.txt
//! ```
//!
//! The input `api-versions.xml` is located automatically under `$ANDROID_HOME`,
//! `$ANDROID_SDK_ROOT` or the default SDK location unless `--api-versions` is given.

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[derive(Default)]
struct ClassInfo {
    since: u32,
    /// Superclass and implemented interfaces, in declaration order.
    supers: Vec<String>,
    /// `name(descriptor)returnType` -> (since, removed)
    methods: BTreeMap<String, (u32, Option<u32>)>,
    /// `name` -> (since, removed)
    fields: BTreeMap<String, (u32, Option<u32>)>,
}

fn main() {
    if let Err(message) = run() {
        eprintln!("error: {message}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mut api_versions: Option<PathBuf> = None;
    let mut classes: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;

    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        let mut take = |name: &str| -> Result<PathBuf, String> {
            args.next()
                .map(PathBuf::from)
                .ok_or_else(|| format!("{name} requires a value"))
        };
        match arg.as_str() {
            "--api-versions" => api_versions = Some(take("--api-versions")?),
            "--classes" => classes = Some(take("--classes")?),
            "--out" => out = Some(take("--out")?),
            "-h" | "--help" => {
                println!(
                    "usage: android-api-metadata --classes <classes.txt> --out <out.txt> \
                     [--api-versions <api-versions.xml>]"
                );
                return Ok(());
            }
            other => return Err(format!("unknown argument: {other}")),
        }
    }

    let classes = classes.ok_or("--classes is required")?;
    let out = out.ok_or("--out is required")?;
    let api_versions = match api_versions {
        Some(path) => path,
        None => locate_api_versions()?,
    };

    let platform = api_versions
        .parent()
        .and_then(Path::parent)
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_owned();

    let requested = read_class_list(&classes)?;
    let all = parse_api_versions(&api_versions)?;

    // Pull in supertypes transitively: a method call on `java/nio/ByteBuffer` may resolve to a
    // member declared on `java/nio/Buffer`, so the lookup performed by the macro has to be able to
    // walk the hierarchy.
    let mut needed = BTreeSet::new();
    let mut queue: VecDeque<String> = requested.iter().cloned().collect();
    while let Some(name) = queue.pop_front() {
        if !needed.insert(name.clone()) {
            continue;
        }
        let Some(info) = all.get(&name) else {
            if requested.contains(&name) {
                return Err(format!(
                    "class {name} listed in {} is not present in {}",
                    classes.display(),
                    api_versions.display()
                ));
            }
            continue;
        };
        for parent in &info.supers {
            queue.push_back(parent.clone());
        }
    }

    let mut text = String::new();
    writeln!(
        text,
        "# Subset of the Android SDK api-versions.xml, generated by `cargo run -p android_api_metadata`."
    )
    .unwrap();
    writeln!(text, "# Source platform: {platform}").unwrap();
    writeln!(
        text,
        "# Do not edit by hand. Add classes to classes.txt and regenerate."
    )
    .unwrap();
    writeln!(text, "#").unwrap();
    writeln!(
        text,
        "# C <class> <since>   class      X <class>   supertype"
    )
    .unwrap();
    writeln!(
        text,
        "# M <name(descriptor)return> <since> [<removed>]   method"
    )
    .unwrap();
    writeln!(text, "# F <name> <since> [<removed>]   field").unwrap();
    writeln!(text, "!platform {platform}").unwrap();

    for name in &needed {
        let Some(info) = all.get(name) else { continue };
        writeln!(text, "C {name} {}", info.since).unwrap();
        for parent in &info.supers {
            writeln!(text, "X {parent}").unwrap();
        }
        for (member, (since, removed)) in &info.methods {
            write_member(&mut text, 'M', member, *since, *removed);
        }
        for (member, (since, removed)) in &info.fields {
            write_member(&mut text, 'F', member, *since, *removed);
        }
    }

    if let Some(dir) = out.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    std::fs::write(&out, text).map_err(|e| format!("{}: {e}", out.display()))?;
    eprintln!(
        "wrote {} ({} classes, from {})",
        out.display(),
        needed.len(),
        api_versions.display()
    );
    Ok(())
}

fn write_member(text: &mut String, kind: char, name: &str, since: u32, removed: Option<u32>) {
    match removed {
        Some(removed) => writeln!(text, "{kind} {name} {since} {removed}").unwrap(),
        None => writeln!(text, "{kind} {name} {since}").unwrap(),
    }
}

fn read_class_list(path: &Path) -> Result<BTreeSet<String>, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(text
        .lines()
        .map(|line| line.split('#').next().unwrap_or("").trim())
        .filter(|line| !line.is_empty())
        .map(str::to_owned)
        .collect())
}

fn locate_api_versions() -> Result<PathBuf, String> {
    let mut roots: Vec<PathBuf> = ["ANDROID_HOME", "ANDROID_SDK_ROOT"]
        .iter()
        .filter_map(|key| std::env::var_os(key))
        .map(PathBuf::from)
        .collect();
    if let Some(home) = std::env::var_os("HOME") {
        let home = PathBuf::from(home);
        roots.push(home.join("Library/Android/sdk"));
        roots.push(home.join("Android/Sdk"));
    }

    let mut best: Option<(u32, PathBuf)> = None;
    for root in roots {
        let Ok(entries) = std::fs::read_dir(root.join("platforms")) else {
            continue;
        };
        for entry in entries.flatten() {
            let name = entry.file_name();
            let Some(level) = name
                .to_str()
                .and_then(|n| n.strip_prefix("android-"))
                .and_then(|n| n.parse::<u32>().ok())
            else {
                continue;
            };
            let candidate = entry.path().join("data/api-versions.xml");
            if candidate.is_file() && best.as_ref().is_none_or(|(b, _)| level > *b) {
                best = Some((level, candidate));
            }
        }
    }

    best.map(|(_, path)| path).ok_or_else(|| {
        "could not find any platforms/android-*/data/api-versions.xml; set ANDROID_HOME or pass \
         --api-versions"
            .to_owned()
    })
}

/// Parses `api-versions.xml`.
///
/// The file is machine-generated with exactly one XML element per line, so a line-oriented scan is
/// sufficient and avoids pulling in an XML parser.
fn parse_api_versions(path: &Path) -> Result<BTreeMap<String, ClassInfo>, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;

    let mut classes: BTreeMap<String, ClassInfo> = BTreeMap::new();
    let mut current: Option<(String, ClassInfo)> = None;

    for (index, line) in text.lines().enumerate() {
        let line = line.trim();
        let number = index + 1;
        if let Some(rest) = line.strip_prefix("<class ") {
            let name = attr(rest, "name")
                .ok_or_else(|| format!("{}:{number}: <class> without name", path.display()))?;
            let since = attr(rest, "since")
                .and_then(|s| s.parse().ok())
                .unwrap_or(1);
            if let Some((name, info)) = current.take() {
                classes.insert(name, info);
            }
            current = Some((
                name,
                ClassInfo {
                    since,
                    ..Default::default()
                },
            ));
        } else if line.starts_with("</class>") {
            if let Some((name, info)) = current.take() {
                classes.insert(name, info);
            }
        } else if let Some(rest) = line
            .strip_prefix("<extends ")
            .or_else(|| line.strip_prefix("<implements "))
        {
            let Some((_, info)) = current.as_mut() else {
                continue;
            };
            if let Some(name) = attr(rest, "name") {
                info.supers.push(name);
            }
        } else if let Some(rest) = line.strip_prefix("<method ") {
            let Some((_, info)) = current.as_mut() else {
                continue;
            };
            if let Some(name) = attr(rest, "name") {
                let since = attr(rest, "since")
                    .and_then(|s| s.parse().ok())
                    .unwrap_or(info.since);
                let removed = attr(rest, "removed").and_then(|s| s.parse().ok());
                info.methods.insert(name, (since.max(info.since), removed));
            }
        } else if let Some(rest) = line.strip_prefix("<field ") {
            let Some((_, info)) = current.as_mut() else {
                continue;
            };
            if let Some(name) = attr(rest, "name") {
                let since = attr(rest, "since")
                    .and_then(|s| s.parse().ok())
                    .unwrap_or(info.since);
                let removed = attr(rest, "removed").and_then(|s| s.parse().ok());
                info.fields.insert(name, (since.max(info.since), removed));
            }
        }
    }
    if let Some((name, info)) = current.take() {
        classes.insert(name, info);
    }

    Ok(classes)
}

/// Reads the value of an XML attribute out of the remainder of an element's start tag.
fn attr(tag: &str, name: &str) -> Option<String> {
    let mut rest = tag;
    loop {
        let start = rest.find(name)?;
        let after = &rest[start + name.len()..];
        let is_word_start = start == 0 || !rest.as_bytes()[start - 1].is_ascii_alphanumeric();
        if is_word_start && after.starts_with("=\"") {
            let value = &after[2..];
            let end = value.find('"')?;
            return Some(unescape(&value[..end]));
        }
        rest = &rest[start + name.len()..];
    }
}

fn unescape(value: &str) -> String {
    if !value.contains('&') {
        return value.to_owned();
    }
    value
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}
