#!/usr/bin/env bash
#
# Computes a deterministic fingerprint of the inputs that determine the
# unienc native binaries. The fingerprint changes if and only if the Rust
# source, Cargo.lock, submodule pointers, or the build recipe change - i.e.
# whenever the committed native binaries would need to be rebuilt.
#
# It relies purely on git object hashes, so it is fast, deterministic and
# independent of the build machine. Submodule commit SHAs are captured
# automatically because they appear as gitlink entries inside the unienc tree.
#
# This script intentionally does NOT include itself in the fingerprint, to
# avoid false positives when the fingerprinting logic is edited.
#
# Usage: compute-unienc-fingerprint.sh [git-ref]   (default: HEAD)
set -euo pipefail

ref="${1:-HEAD}"

# unienc-tree covers all tracked Rust source, Cargo.toml/Cargo.lock and the
# submodule pointers (external/*) via their gitlink entries.
unienc="$(git rev-parse "${ref}:InstantReplay.Externals/unienc")"
# build-workflow captures the build recipe itself (targets, feature flags, ...).
workflow="$(git rev-parse "${ref}:.github/workflows/build-unienc.yml")"
# localize-script is a build-time post-processing step for the Apple staticlib.
localize="$(git rev-parse "${ref}:.github/scripts/localize-apple-staticlib.sh")"

cat <<EOF
# unienc native-build source fingerprint
# Auto-generated by build-unienc.yml. Do not edit by hand.
unienc-tree: ${unienc}
build-workflow: ${workflow}
localize-script: ${localize}
EOF
