//! Support code for the JNI wrappers generated by [`java_api_macros::java_api`].
//!
//! The declarations themselves live in [`crate::bindings`].
//!
//! # Why this exists
//!
//! Calling the Android Java API through `jni::JNIEnv::call_method` names the method and its
//! signature as plain strings. Nothing records which API level the method was introduced in, so a
//! call to a method that does not exist on the minimum supported device compiles and links
//! successfully and only fails at run time — as a `NoSuchMethodError` that, being left pending as a
//! JNI exception, terminates the process.
//!
//! The `java_api!` macro checks every declaration against the Android SDK's `api-versions.xml`
//! (see `java-api/android-api-versions.txt` and the `android_api_metadata` tool) and refuses to
//! compile a call to a member introduced after [`MIN_API_LEVEL`] unless the declaration is
//! annotated with `#[api(N)]`. Such a member takes an additional [`ApiLevel<N>`] parameter, which
//! can only be obtained from [`ApiLevel::check`], so the run-time guard cannot be forgotten.

use std::sync::OnceLock;

use jni::JNIEnv;
use jni::errors::{Error, Result as JniResult};

use crate::error::Result;
use crate::java::attach_current_thread;

/// Minimum Android API level the native library is built for.
///
/// This matches the `--platform` argument passed to `cargo ndk` by `.github/workflows/build-unienc.yml`.
pub const MIN_API_LEVEL: u32 = 26;

/// Discards a pending JNI exception, after describing it to the log.
///
/// A JNI exception that is left pending terminates the process as soon as control returns to the
/// JVM, so every failed call has to clear it. The error itself is propagated unchanged.
#[inline]
pub fn checked<T>(env: &mut JNIEnv, result: JniResult<T>) -> JniResult<T> {
    if let Err(Error::JavaException) = &result {
        let _ = env.exception_describe();
        let _ = env.exception_clear();
    }
    result
}

/// Same as [`checked`], but without writing the exception to the log.
///
/// Used for calls that are expected to throw as part of normal operation, which are marked
/// `#[may_throw]` in the declaration.
#[inline]
pub fn checked_quiet<T>(env: &mut JNIEnv, result: JniResult<T>) -> JniResult<T> {
    if let Err(Error::JavaException) = &result {
        let _ = env.exception_clear();
    }
    result
}

/// Proof that the device runs on API level `N` or later.
///
/// Obtained from [`ApiLevel::check`]. Wrappers for members introduced after [`MIN_API_LEVEL`] take
/// one, so they cannot be called without the corresponding run-time check.
#[derive(Debug, Clone, Copy)]
pub struct ApiLevel<const N: u32>(());

impl<const N: u32> ApiLevel<N> {
    /// The API level this witness stands for.
    pub const LEVEL: u32 = N;

    /// Returns the witness when the device is on API level `N` or later, and `None` otherwise.
    pub fn check() -> Result<Option<Self>> {
        Ok((device_api_level()? >= N).then_some(Self(())))
    }

    /// Weakens the witness to a lower API level.
    pub const fn downgrade<const M: u32>(self) -> ApiLevel<M> {
        const { assert!(M <= N, "cannot strengthen an ApiLevel witness") }
        ApiLevel(())
    }
}

static API_LEVEL: OnceLock<u32> = OnceLock::new();

/// Reads `android.os.Build.VERSION.SDK_INT`, caching the result.
pub fn device_api_level() -> Result<u32> {
    if let Some(&level) = API_LEVEL.get() {
        return Ok(level);
    }
    let env = &mut attach_current_thread()?;
    let level = crate::bindings::BuildVersion::sdk_int(env)?.max(0) as u32;
    let _ = API_LEVEL.set(level);
    Ok(level)
}
