pub const GRAPHICS_FORMAT_TO_VULKAN: [Option<ash::vk::Format>; 152] = [
    Some(ash::vk::Format::UNDEFINED),                 // None
    Some(ash::vk::Format::R8_SRGB),                   // R8_SRGB
    Some(ash::vk::Format::R8G8_SRGB),                 // R8G8_SRGB
    Some(ash::vk::Format::R8G8B8_SRGB),               // R8G8B8_SRGB
    Some(ash::vk::Format::R8G8B8A8_SRGB),             // R8G8B8A8_SRGB
    Some(ash::vk::Format::R8_UNORM),                  // R8_UNorm
    Some(ash::vk::Format::R8G8_UNORM),                // R8G8_UNorm
    Some(ash::vk::Format::R8G8B8_UNORM),              // R8G8B8_UNorm
    Some(ash::vk::Format::R8G8B8A8_UNORM),            // R8G8B8A8_UNorm
    Some(ash::vk::Format::R8_SNORM),                  // R8_SNorm
    Some(ash::vk::Format::R8G8_SNORM),                // R8G8_SNorm
    Some(ash::vk::Format::R8G8B8_SNORM),              // R8G8B8_SNorm
    Some(ash::vk::Format::R8G8B8A8_SNORM),            // R8G8B8A8_SNorm
    Some(ash::vk::Format::R8_UINT),                   // R8_UInt
    Some(ash::vk::Format::R8G8_UINT),                 // R8G8_UInt
    Some(ash::vk::Format::R8G8B8_UINT),               // R8G8B8_UInt
    Some(ash::vk::Format::R8G8B8A8_UINT),             // R8G8B8A8_UInt
    Some(ash::vk::Format::R8_SINT),                   // R8_SInt
    Some(ash::vk::Format::R8G8_SINT),                 // R8G8_SInt
    Some(ash::vk::Format::R8G8B8_SINT),               // R8G8B8_SInt
    Some(ash::vk::Format::R8G8B8A8_SINT),             // R8G8B8A8_SInt
    Some(ash::vk::Format::R16_UNORM),                 // R16_UNorm
    Some(ash::vk::Format::R16G16_UNORM),              // R16G16_UNorm
    Some(ash::vk::Format::R16G16B16_UNORM),           // R16G16B16_UNorm
    Some(ash::vk::Format::R16G16B16A16_UNORM),        // R16G16B16A16_UNorm
    Some(ash::vk::Format::R16_SNORM),                 // R16_SNorm
    Some(ash::vk::Format::R16G16_SNORM),              // R16G16_SNorm
    Some(ash::vk::Format::R16G16B16_SNORM),           // R16G16B16_SNorm
    Some(ash::vk::Format::R16G16B16A16_SNORM),        // R16G16B16A16_SNorm
    Some(ash::vk::Format::R16_UINT),                  // R16_UInt
    Some(ash::vk::Format::R16G16_UINT),               // R16G16_UInt
    Some(ash::vk::Format::R16G16B16_UINT),            // R16G16B16_UInt
    Some(ash::vk::Format::R16G16B16A16_UINT),         // R16G16B16A16_UInt
    Some(ash::vk::Format::R16_SINT),                  // R16_SInt
    Some(ash::vk::Format::R16G16_SINT),               // R16G16_SInt
    Some(ash::vk::Format::R16G16B16_SINT),            // R16G16B16_SInt
    Some(ash::vk::Format::R16G16B16A16_SINT),         // R16G16B16A16_SInt
    Some(ash::vk::Format::R32_UINT),                  // R32_UInt
    Some(ash::vk::Format::R32G32_UINT),               // R32G32_UInt
    Some(ash::vk::Format::R32G32B32_UINT),            // R32G32B32_UInt
    Some(ash::vk::Format::R32G32B32A32_UINT),         // R32G32B32A32_UInt
    Some(ash::vk::Format::R32_SINT),                  // R32_SInt
    Some(ash::vk::Format::R32G32_SINT),               // R32G32_SInt
    Some(ash::vk::Format::R32G32B32_SINT),            // R32G32B32_SInt
    Some(ash::vk::Format::R32G32B32A32_SINT),         // R32G32B32A32_SInt
    Some(ash::vk::Format::R16_SFLOAT),                // R16_SFloat
    Some(ash::vk::Format::R16G16_SFLOAT),             // R16G16_SFloat
    Some(ash::vk::Format::R16G16B16_SFLOAT),          // R16G16B16_SFloat
    Some(ash::vk::Format::R16G16B16A16_SFLOAT),       // R16G16B16A16_SFloat
    Some(ash::vk::Format::R32_SFLOAT),                // R32_SFloat
    Some(ash::vk::Format::R32G32_SFLOAT),             // R32G32_SFloat
    Some(ash::vk::Format::R32G32B32_SFLOAT),          // R32G32B32_SFloat

    None,
    None,
    None,
    None,

    Some(ash::vk::Format::B8G8R8_SRGB),               // B8G8R8_SRGB,
    Some(ash::vk::Format::B8G8R8A8_SRGB),             // B8G8R8A8_SRGB,
    Some(ash::vk::Format::B8G8R8_UNORM),              // B8G8R8_UNorm,
    Some(ash::vk::Format::B8G8R8A8_UNORM),            // B8G8R8A8_UNorm,
    Some(ash::vk::Format::B8G8R8_SNORM),              // B8G8R8_SNorm,
    Some(ash::vk::Format::B8G8R8A8_SNORM),            // B8G8R8A8_SNorm,
    Some(ash::vk::Format::B8G8R8_UINT),               // B8G8R8_UInt,
    Some(ash::vk::Format::B8G8R8A8_UINT),             // B8G8R8A8_UInt,
    Some(ash::vk::Format::B8G8R8_SINT),               // B8G8R8_SInt,
    Some(ash::vk::Format::B8G8R8A8_SINT),             // B8G8R8A8_SInt,
    Some(ash::vk::Format::R4G4B4A4_UNORM_PACK16),     // R4G4B4A4_UNormPack16,
    Some(ash::vk::Format::B4G4R4A4_UNORM_PACK16),     // B4G4R4A4_UNormPack16,
    Some(ash::vk::Format::R5G6B5_UNORM_PACK16),       // R5G6B5_UNormPack16,
    Some(ash::vk::Format::R5G6B5_UNORM_PACK16),       // B5G6R5_UNormPack16,
    Some(ash::vk::Format::R5G5B5A1_UNORM_PACK16),     // R5G5B5A1_UNormPack16,
    Some(ash::vk::Format::A1R5G5B5_UNORM_PACK16),     // B5G5R5A1_UNormPack16,
    Some(ash::vk::Format::B5G5R5A1_UNORM_PACK16),     // A1R5G5B5_UNormPack16,
    Some(ash::vk::Format::E5B9G9R9_UFLOAT_PACK32),    // E5B9G9R9_UFloatPack32,
    Some(ash::vk::Format::B10G11R11_UFLOAT_PACK32),   // B10G11R11_UFloatPack32,
    Some(ash::vk::Format::A2B10G10R10_UNORM_PACK32),  // A2B10G10R10_UNormPack32,
    Some(ash::vk::Format::A2B10G10R10_UINT_PACK32),   // A2B10G10R10_UIntPack32,
    Some(ash::vk::Format::A2B10G10R10_SINT_PACK32),   // A2B10G10R10_SIntPack32,
    Some(ash::vk::Format::A2R10G10B10_UNORM_PACK32),  // A2R10G10B10_UNormPack32,
    Some(ash::vk::Format::A2R10G10B10_UINT_PACK32),   // A2R10G10B10_UIntPack32,
    Some(ash::vk::Format::A2R10G10B10_SINT_PACK32),   // A2R10G10B10_SIntPack32,
    Some(ash::vk::Format::UNDEFINED),                 // A2R10G10B10_XRSRGBPack32,
    Some(ash::vk::Format::UNDEFINED),                 // A2R10G10B10_XRUNormPack32,
    Some(ash::vk::Format::UNDEFINED),                 // R10G10B10_XRSRGBPack32,
    Some(ash::vk::Format::UNDEFINED),                 // R10G10B10_XRUNormPack32,
    Some(ash::vk::Format::UNDEFINED),                 // A10R10G10B10_XRSRGBPack32,
    Some(ash::vk::Format::UNDEFINED),                 // A10R10G10B10_XRUNormPack32,

    None,
    None,
    None,

    Some(ash::vk::Format::D16_UNORM),                 // D16_UNorm
    Some(ash::vk::Format::X8_D24_UNORM_PACK32),       // D24_UNorm
    Some(ash::vk::Format::D24_UNORM_S8_UINT),         // D24_UNorm_S8_UInt
    Some(ash::vk::Format::D32_SFLOAT),                // D32_SFloat
    Some(ash::vk::Format::D32_SFLOAT_S8_UINT),        // D32_SFloat_S8_UInt
    Some(ash::vk::Format::S8_UINT),                   // S8_UInt
    Some(ash::vk::Format::BC1_RGBA_SRGB_BLOCK),       // RGBA_DXT1_SRGB
    Some(ash::vk::Format::BC1_RGBA_UNORM_BLOCK),      // RGBA_DXT1_UNorm
    Some(ash::vk::Format::BC2_SRGB_BLOCK),            // RGBA_DXT3_SRGB
    Some(ash::vk::Format::BC2_UNORM_BLOCK),           // RGBA_DXT3_UNorm
    Some(ash::vk::Format::BC3_SRGB_BLOCK),            // RGBA_DXT5_SRGB
    Some(ash::vk::Format::BC3_UNORM_BLOCK),           // RGBA_DXT5_UNorm
    Some(ash::vk::Format::BC4_UNORM_BLOCK),           // R_BC4_UNorm
    Some(ash::vk::Format::BC4_SNORM_BLOCK),           // R_BC4_SNorm
    Some(ash::vk::Format::BC5_UNORM_BLOCK),           // RG_BC5_UNorm
    Some(ash::vk::Format::BC5_SNORM_BLOCK),           // RG_BC5_SNorm
    Some(ash::vk::Format::BC6H_UFLOAT_BLOCK),         // RGB_BC6H_UFloat
    Some(ash::vk::Format::BC6H_SFLOAT_BLOCK),         // RGB_BC6H_SFloat
    Some(ash::vk::Format::BC7_SRGB_BLOCK),            // RGBA_BC7_SRGB
    Some(ash::vk::Format::BC7_UNORM_BLOCK),           // RGBA_BC7_UNorm
    Some(ash::vk::Format::UNDEFINED),                 // RGB_PVRTC_2Bpp_SRGB
    Some(ash::vk::Format::UNDEFINED),                 // RGB_PVRTC_2Bpp_UNorm
    Some(ash::vk::Format::UNDEFINED),                 // RGB_PVRTC_4Bpp_SRGB
    Some(ash::vk::Format::UNDEFINED),                 // RGB_PVRTC_4Bpp_UNorm
    Some(ash::vk::Format::UNDEFINED),                 // RGBA_PVRTC_2Bpp_SRGB
    Some(ash::vk::Format::UNDEFINED),                 // RGBA_PVRTC_2Bpp_UNorm
    Some(ash::vk::Format::UNDEFINED),                 // RGBA_PVRTC_4Bpp_SRGB
    Some(ash::vk::Format::UNDEFINED),                 // RGBA_PVRTC_4Bpp_UNorm
    Some(ash::vk::Format::ETC2_R8G8B8_UNORM_BLOCK),   // RGB_ETC_UNorm
    Some(ash::vk::Format::ETC2_R8G8B8_SRGB_BLOCK),    // RGB_ETC2_SRGB
    Some(ash::vk::Format::ETC2_R8G8B8_UNORM_BLOCK),   // RGB_ETC2_UNorm
    Some(ash::vk::Format::ETC2_R8G8B8A1_SRGB_BLOCK),  // RGB_A1_ETC2_SRGB
    Some(ash::vk::Format::ETC2_R8G8B8A1_UNORM_BLOCK), // RGB_A1_ETC2_UNorm
    Some(ash::vk::Format::ETC2_R8G8B8A8_SRGB_BLOCK),  // RGBA_ETC2_SRGB
    Some(ash::vk::Format::ETC2_R8G8B8A8_UNORM_BLOCK), // RGBA_ETC2_UNorm
    Some(ash::vk::Format::EAC_R11_UNORM_BLOCK),       // R_EAC_UNorm
    Some(ash::vk::Format::EAC_R11_SNORM_BLOCK),       // R_EAC_SNorm
    Some(ash::vk::Format::EAC_R11G11_UNORM_BLOCK),    // RG_EAC_UNorm
    Some(ash::vk::Format::EAC_R11G11_SNORM_BLOCK),    // RG_EAC_SNorm
    Some(ash::vk::Format::ASTC_4X4_SRGB_BLOCK),       // RGBA_ASTC4X4_SRGB
    Some(ash::vk::Format::ASTC_4X4_UNORM_BLOCK),      // RGBA_ASTC4X4_UNorm
    Some(ash::vk::Format::ASTC_5X5_SRGB_BLOCK),       // RGBA_ASTC5X5_SRGB
    Some(ash::vk::Format::ASTC_5X5_UNORM_BLOCK),      // RGBA_ASTC5X5_UNorm
    Some(ash::vk::Format::ASTC_6X6_SRGB_BLOCK),       // RGBA_ASTC6X6_SRGB
    Some(ash::vk::Format::ASTC_6X6_UNORM_BLOCK),      // RGBA_ASTC6X6_UNorm
    Some(ash::vk::Format::ASTC_8X8_SRGB_BLOCK),       // RGBA_ASTC8X8_SRGB
    Some(ash::vk::Format::ASTC_8X8_UNORM_BLOCK),      // RGBA_ASTC8X8_UNorm
    Some(ash::vk::Format::ASTC_10X10_SRGB_BLOCK),     // RGBA_ASTC10X10_SRGB
    Some(ash::vk::Format::ASTC_10X10_UNORM_BLOCK),    // RGBA_ASTC10X10_UNorm
    Some(ash::vk::Format::ASTC_12X12_SRGB_BLOCK),     // RGBA_ASTC12X12_SRGB
    Some(ash::vk::Format::ASTC_12X12_UNORM_BLOCK),    // RGBA_ASTC12X12_UNorm
    Some(ash::vk::Format::UNDEFINED),                 // YUV2
    Some(ash::vk::Format::UNDEFINED),                 // DepthAuto
    Some(ash::vk::Format::UNDEFINED),                 // ShadowAuto
    Some(ash::vk::Format::UNDEFINED),                 // VideoAuto
    Some(ash::vk::Format::ASTC_4X4_UNORM_BLOCK),      // RGBA_ASTC4X4_UFloat
    Some(ash::vk::Format::ASTC_5X5_UNORM_BLOCK),      // RGBA_ASTC5X5_UFloat
    Some(ash::vk::Format::ASTC_6X6_UNORM_BLOCK),      // RGBA_ASTC6X6_UFloat
    Some(ash::vk::Format::ASTC_8X8_UNORM_BLOCK),      // RGBA_ASTC8X8_UFloat
    Some(ash::vk::Format::ASTC_10X10_UNORM_BLOCK),    // RGBA_ASTC10X10_UFloat
    Some(ash::vk::Format::ASTC_12X12_UNORM_BLOCK),    // RGBA_ASTC12X12_UFloat
    Some(ash::vk::Format::D16_UNORM_S8_UINT),         // D16_UNorm_S8_UInt
];