[package]
name = "instant-replay-transcoder"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.97"
turbojpeg = "1.3.0"
windows = { version = "0.60.0", features = [
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
] }
